nmHoistingLimits: workspaces
nodeLinker: node-modules

npmRegistryServer: ${NPM_REPO}
npmAuthToken: ${NPM_REPO_AUTH_TOKEN}
npmAlwaysAuth: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.cjs
