const packageJson = {
  name: 'projen-ts',
  devDependencies: {
    projen: '*',
  },
  bundledDependencies: [],
  main: 'lib/index.js',
  license: 'Apache-2.0',
  version: '0.0.0',
  types: 'lib/index.d.ts',
  '//': '~~ ' + 'Generated by projen. ' + 'To modify, edit .projenrc.js and run "npx projen".',
};

export const buildPackageJson = (): string => {
  return JSON.stringify(packageJson, null, 2);
};
