export function generateTestConfigsTs() {
  return `
// ~~ This file is owned by caws-blueprints and is generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as fs from 'fs';
import merge from 'ts-deepmerge';
import * as path from 'path';
import { getFilenamesInPath } from './files';
import { Options } from '../blueprint';

const PATH_TO_SRC = 'src';
const PATH_TO_CONFIGS = path.join(PATH_TO_SRC, 'test-configs');

type TestConfigFromFile = Omit<Options, 'outdir'>;

export function listTestConfigNames(): string[] {
  return (
    getFilenamesInPath(PATH_TO_CONFIGS)
      // chop off ".json"
      .map(p => p.toString().slice(0, -'.json'.length))
  );
}

export function getTestConfig(name: string): TestConfigFromFile {
  const defaultsConfig = JSON.parse(fs.readFileSync(path.join(PATH_TO_SRC, 'defaults.json')).toString());
  const testConfig = JSON.parse(fs.readFileSync(path.join(PATH_TO_CONFIGS, \`\${name}.json\`)).toString());
  return merge(defaultsConfig, testConfig) as unknown as TestConfigFromFile;
}

export interface TestConfig {
  name: string;
  config: TestConfigFromFile;
}

export function allTestConfigs(): TestConfig[] {
  return listTestConfigNames().map(configName => ({
    name: configName,
    config: getTestConfig(configName),
  }));
}
`;
}
