export function generateOutdirTs() {
  return `
// ~~ This file is owned by caws-blueprints and is generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as fs from 'fs';

export function prepareNewOutdir(): string {
  const outdir = fs.mkdtempSync('unittest-outdir-');
  console.debug(\`outdir: \${outdir}\`);

  if (fs.existsSync(outdir)) {
    // have to check, else \`rmSync\` throws an error.
    // Clean up the directory. If we don't clean up, then \`mkdirSync\` will throw an error.
    fs.rmSync(outdir, { recursive: true });
  }
  fs.mkdirSync(outdir);

  return outdir;
}

export function cleanUpOutdir(outdir: string): void {
  console.debug(\`cleaning up outdir: \${outdir}\`);
  if (fs.existsSync(outdir)) {
    // have to check for existence, else \`rmSync\` throws an error.
    fs.rmSync(outdir, { recursive: true });
  }
}
`;
}
