name: Build PR
on: pull_request

jobs:
  build-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'
      - run: |
          yarn --immutable-cache
          yarn build
